language: php

env:
  global:
    - XDEBUG_MODE=coverage

php:
  - 8.0
  - 8.1

before_script:
  - 'COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction'

script: vendor/bin/codecept run --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
